# Generated by Django 4.2.7 on 2023-11-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_time_of_publication']},
        ),
    ]
